--Table: smp

--DROP SEQUENCE IF EXISTS smp_id CASCADE;
CREATE SEQUENCE smp_id AS BIGINT;

--DROP TABLE IF EXISTS smp CASCADE;
CREATE TABLE smp(
	pdf_file 		BYTEA NOT NULL,
	id        		BIGINT PRIMARY KEY
);